export type BlockedResponseProvider = "cloudflare" | "cloudfront" | "cdn";

export type BlockedResponseReason = "explicit-challenge" | "generated-error" | "corroborated-status";

export type BlockedResponseEvidenceSource = "status" | "header" | "title" | "body";

export type BlockedResponseHeaderValue = string | readonly string[] | undefined;

export type BlockedResponseHeaders = Headers | Readonly<Record<string, BlockedResponseHeaderValue>>;

export interface BlockedResponseInput {
    readonly status: number;
    readonly headers?: BlockedResponseHeaders;
    readonly body: string;
}

export interface BlockedResponseEvidence {
    readonly source: BlockedResponseEvidenceSource;
    readonly signal: string;
    readonly name?: string;
    readonly value: string | number;
}

export interface BlockedResponseResult {
    readonly blocked: boolean;
    readonly provider: BlockedResponseProvider | null;
    readonly reason: BlockedResponseReason | null;
    readonly evidence: readonly BlockedResponseEvidence[];
}

const NO_EVIDENCE = Object.freeze([]) as readonly BlockedResponseEvidence[];

const NOT_BLOCKED: BlockedResponseResult = Object.freeze({
    blocked: false,
    provider: null,
    reason: null,
    evidence: NO_EVIDENCE,
});

type NormalizedHeaders = Readonly<Record<string, string>>;

interface CdnHeaderMatch {
    readonly provider: BlockedResponseProvider;
    readonly name: string;
    readonly value: string;
}

interface CdnHeaderRule {
    readonly name: string;
    readonly provider: BlockedResponseProvider;
    readonly matches: (value: string) => boolean;
}

const HTML_DOCUMENT_START = /^\uFEFF?\s*(?:<!doctype\s+html\b|<html\b|<head\b|<title\b)/i;
const JAVASCRIPT_CONTENT_TYPE = /(?:java|ecma)script/i;
const CLOUDFRONT_ERROR_BODY = /\berror:\s*the request could not be satisfied\b/i;
const CLOUDFRONT_GENERATOR = /\bgenerated by cloudfront\s*\(cloudfront\)/i;

const CDN_HEADER_RULES: readonly CdnHeaderRule[] = Object.freeze([
    Object.freeze({
        name: "cf-ray",
        provider: "cloudflare" as const,
        matches: (value: string): boolean => value.trim().length > 0,
    }),
    Object.freeze({
        name: "server",
        provider: "cloudflare" as const,
        matches: (value: string): boolean => /(?:^|\s|\()cloudflare(?:$|\s|\))/i.test(value),
    }),
    Object.freeze({
        name: "x-amz-cf-id",
        provider: "cloudfront" as const,
        matches: (value: string): boolean => value.trim().length > 0,
    }),
    Object.freeze({
        name: "server",
        provider: "cloudfront" as const,
        matches: (value: string): boolean => /\bcloudfront\b/i.test(value),
    }),
    Object.freeze({
        name: "via",
        provider: "cloudfront" as const,
        matches: (value: string): boolean => /\bcloudfront\b/i.test(value),
    }),
    Object.freeze({
        name: "x-cache",
        provider: "cloudfront" as const,
        matches: (value: string): boolean => /\bcloudfront\b/i.test(value),
    }),
    Object.freeze({
        name: "server",
        provider: "cdn" as const,
        matches: (value: string): boolean => /^(?:akamaighost|fastly|varnish|sucuri\/cloudproxy)\b/i.test(value.trim()),
    }),
    Object.freeze({
        name: "via",
        provider: "cdn" as const,
        matches: (value: string): boolean => /\b(?:akamai|fastly|varnish)\b/i.test(value),
    }),
    Object.freeze({
        name: "x-served-by",
        provider: "cdn" as const,
        matches: (value: string): boolean => /(?:^|[\s,])cache-/i.test(value),
    }),
    Object.freeze({
        name: "x-akamai-transformed",
        provider: "cdn" as const,
        matches: (value: string): boolean => value.trim().length > 0,
    }),
    Object.freeze({
        name: "x-sucuri-id",
        provider: "cdn" as const,
        matches: (value: string): boolean => value.trim().length > 0,
    }),
]);

const STATUS_DENIAL_PATTERNS: Readonly<Record<number, readonly Readonly<{ pattern: RegExp; label: string }>[]>> =
    Object.freeze({
        403: Object.freeze([
            Object.freeze({ pattern: /\baccess\s+denied\b/i, label: "access denied" }),
            // eslint-disable-next-line security/detect-unsafe-regex -- literal-heavy, no nested/ambiguous quantifiers — not exploitable
            Object.freeze({ pattern: /\brequest\s+(?:was\s+)?blocked\b/i, label: "request blocked" }),
        ]),
        429: Object.freeze([
            Object.freeze({ pattern: /\btoo many requests\b/i, label: "too many requests" }),
            Object.freeze({ pattern: /\brate[ -]?limit(?:ed| exceeded)?\b/i, label: "rate limit" }),
        ]),
        503: Object.freeze([
            Object.freeze({ pattern: /\bservice unavailable\b/i, label: "service unavailable" }),
            Object.freeze({ pattern: /\btemporarily unavailable\b/i, label: "temporarily unavailable" }),
            Object.freeze({ pattern: /\bchecking your browser\b/i, label: "browser check" }),
        ]),
    });

const normalizeHeaderValue = (value: BlockedResponseHeaderValue): string | null => {
    if (typeof value === "string") return value;
    if (Array.isArray(value)) return value.join(", ");
    return null;
};

const normalizeHeaderEntries = (
    entries: readonly (readonly [string, BlockedResponseHeaderValue])[]
): NormalizedHeaders =>
    Object.freeze(
        entries.reduce<Record<string, string>>((normalized, [name, rawValue]) => {
            const value = normalizeHeaderValue(rawValue);
            return value === null ? normalized : { ...normalized, [name.toLowerCase()]: value };
        }, {})
    );

const normalizeHeaders = (headers: BlockedResponseHeaders | undefined): NormalizedHeaders => {
    if (!headers) return Object.freeze({});
    if (typeof Headers !== "undefined" && headers instanceof Headers) {
        return normalizeHeaderEntries(Array.from(headers.entries()));
    }
    return normalizeHeaderEntries(Object.entries(headers));
};

const evidence = (
    source: BlockedResponseEvidenceSource,
    signal: string,
    value: string | number,
    name?: string
): BlockedResponseEvidence => Object.freeze({ source, signal, ...(name ? { name } : {}), value });

const blockedResult = (
    provider: BlockedResponseProvider,
    reason: BlockedResponseReason,
    items: readonly BlockedResponseEvidence[]
): BlockedResponseResult =>
    Object.freeze({
        blocked: true,
        provider,
        reason,
        evidence: Object.freeze([...items]),
    });

const isHtmlDocument = (headers: NormalizedHeaders, body: string): boolean =>
    !JAVASCRIPT_CONTENT_TYPE.test(headers["content-type"] ?? "") && HTML_DOCUMENT_START.test(body);

// eslint-disable-next-line security/detect-unsafe-regex -- single lazy scan to the next literal, no nested quantifiers — not exploitable
const normalizedTitle = (body: string): string | null => {
    const match = /<title(?:\s[^>]*)?>([\s\S]*?)<\/title\s*>/i.exec(body);
    return match ? match[1].replace(/\s+/g, " ").trim() : null;
};

const cloudflareDocumentEvidence = (body: string): readonly BlockedResponseEvidence[] => {
    const title = normalizedTitle(body);
    const titleMatch =
        title && ["just a moment...", "attention required! | cloudflare"].includes(title.toLowerCase())
            ? evidence("title", "cloudflare-challenge-title", title)
            : null;
    const bodyMarker = /\/cdn-cgi\/challenge-platform\//i.test(body)
        ? "/cdn-cgi/challenge-platform/"
        : /\/\?bm-verify=/i.test(body)
          ? "/?bm-verify="
          : /\b(?:window\.)?_cf_chl_opt\b/i.test(body)
            ? "_cf_chl_opt"
            : /\bchecking your browser\b/i.test(body) && /\bcloudflare\b/i.test(body)
              ? "Cloudflare browser check"
              : null;
    const bodyMatch = bodyMarker ? evidence("body", "cloudflare-challenge-body", bodyMarker) : null;
    return Object.freeze([titleMatch, bodyMatch].filter((item): item is BlockedResponseEvidence => item !== null));
};

const cdnHeaderMatches = (headers: NormalizedHeaders): readonly CdnHeaderMatch[] =>
    Object.freeze(
        CDN_HEADER_RULES.flatMap((rule) => {
            const value = headers[rule.name];
            return value && rule.matches(value)
                ? [Object.freeze({ provider: rule.provider, name: rule.name, value })]
                : [];
        })
    );

const providerFromHeaderMatches = (matches: readonly CdnHeaderMatch[]): BlockedResponseProvider => {
    if (matches.some((match) => match.provider === "cloudflare")) return "cloudflare";
    if (matches.some((match) => match.provider === "cloudfront")) return "cloudfront";
    return "cdn";
};

const denialBodyMarker = (status: number, body: string): string | null => {
    const patterns = STATUS_DENIAL_PATTERNS[status] ?? [];
    return patterns.find(({ pattern }) => pattern.test(body))?.label ?? null;
};

/**
 * Detects strongly evidenced CDN/WAF block responses without I/O or logging.
 *
 * Generic 403/429/503 responses are only classified when status, a recognized CDN header,
 * and a status-appropriate HTML denial body corroborate one another. Explicit Cloudflare
 * challenge and CloudFront-generated-error signals can be decisive on their own.
 */
export const detectBlockedResponse = (input: BlockedResponseInput): BlockedResponseResult => {
    const headers = normalizeHeaders(input.headers);
    const body = typeof input.body === "string" ? input.body : "";
    const cfMitigated = headers["cf-mitigated"];

    if (cfMitigated?.split(",").some((value) => value.trim().toLowerCase() === "challenge")) {
        return blockedResult("cloudflare", "explicit-challenge", [
            evidence("header", "cloudflare-challenge-header", cfMitigated, "cf-mitigated"),
        ]);
    }

    const htmlDocument = isHtmlDocument(headers, body);
    if (htmlDocument) {
        const cloudflareEvidence = cloudflareDocumentEvidence(body);
        if (cloudflareEvidence.length > 0) {
            return blockedResult("cloudflare", "explicit-challenge", cloudflareEvidence);
        }
    }

    const errorStatus =
        Number.isInteger(input.status) && input.status >= 400 && input.status <= 599 && input.status !== 404;
    const cloudfrontErrorHeader = headers["x-cache"];
    if (errorStatus && cloudfrontErrorHeader && /\berror from cloudfront\b/i.test(cloudfrontErrorHeader)) {
        const requestId = headers["x-amz-cf-id"];
        return blockedResult("cloudfront", "generated-error", [
            evidence("status", "error-http-status", input.status),
            evidence("header", "cloudfront-generated-error-header", cloudfrontErrorHeader, "x-cache"),
            ...(requestId ? [evidence("header", "cloudfront-request-id-header", requestId, "x-amz-cf-id")] : []),
        ]);
    }

    if (errorStatus && htmlDocument && CLOUDFRONT_ERROR_BODY.test(body) && CLOUDFRONT_GENERATOR.test(body)) {
        return blockedResult("cloudfront", "generated-error", [
            evidence("status", "error-http-status", input.status),
            evidence("body", "cloudfront-generated-error-body", "Generated by cloudfront (CloudFront)"),
        ]);
    }

    const denialMarker = htmlDocument ? denialBodyMarker(input.status, body) : null;
    if (denialMarker) {
        const headerMatches = cdnHeaderMatches(headers);
        if (headerMatches.length > 0) {
            return blockedResult(providerFromHeaderMatches(headerMatches), "corroborated-status", [
                evidence("status", "blocked-http-status", input.status),
                ...headerMatches.map((match) => evidence("header", "cdn-response-header", match.value, match.name)),
                evidence("body", "status-matched-denial-body", denialMarker),
            ]);
        }
    }

    return NOT_BLOCKED;
};

export default detectBlockedResponse;
