name: Plumber

on:
  push: {}
  pull_request: null
  workflow_dispatch: null

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  plumber:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: getplumber/plumber@56369e7d43c4878049ee8ec6c2d600c21af45c4e # v0.4.12, 2026-07-20
        with:
          score-push: true
