name: Plumber

on:
  push: {}
  pull_request: null
  workflow_dispatch: null

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  plumber:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: getplumber/plumber@932f3b5b87ffdd6f3101a2e6ce5a223320960849 # v0.4.12, 2026-07-20
        with:
          score-push: true
